import type { Job, Question } from "./types"

export const SAMPLE_JOBS: Job[] = [
  {
    id: "job-1",
    title: "Senior Frontend Engineer",
    company: "TechCorp Inc.",
    description:
      "We are looking for a Senior Frontend Engineer to join our team. You will be responsible for building and maintaining our web applications using React, TypeScript, and modern frontend technologies. Experience with state management, testing, and CI/CD pipelines is a plus. You should have strong problem-solving skills and the ability to work in an agile environment.",
    requiredSkills: [
      "react",
      "typescript",
      "javascript",
      "css",
      "html",
      "git",
      "agile",
      "testing",
    ],
    weights: {
      skills: 35,
      experience: 25,
      projects: 20,
      achievements: 10,
      education: 10,
    },
    minCvScore: 50,
    minTestScore: 60,
    recruiterId: "recruiter-default",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job-2",
    title: "Data Scientist",
    company: "AnalyticsHub",
    description:
      "Join our data science team to build machine learning models, analyze large datasets, and drive data-informed decisions. You should be proficient in Python, have experience with ML frameworks like TensorFlow or PyTorch, and understand statistical analysis. Knowledge of NLP and deep learning is highly valued.",
    requiredSkills: [
      "python",
      "machine learning",
      "deep learning",
      "tensorflow",
      "pytorch",
      "sql",
      "data analysis",
      "nlp",
    ],
    weights: {
      skills: 30,
      experience: 20,
      projects: 25,
      achievements: 15,
      education: 10,
    },
    minCvScore: 55,
    minTestScore: 65,
    recruiterId: "recruiter-default",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job-3",
    title: "Full Stack Developer",
    company: "StartupLabs",
    description:
      "We need a versatile full stack developer who can work on both frontend and backend. You should be comfortable with React, Node.js, databases (SQL and NoSQL), and deploying to cloud platforms. We value developers who can own features end-to-end and thrive in a fast-paced startup environment.",
    requiredSkills: [
      "react",
      "node",
      "javascript",
      "typescript",
      "sql",
      "mongodb",
      "docker",
      "aws",
    ],
    weights: {
      skills: 30,
      experience: 20,
      projects: 25,
      achievements: 10,
      education: 15,
    },
    minCvScore: 45,
    minTestScore: 55,
    recruiterId: "recruiter-default",
    createdAt: new Date().toISOString(),
  },
]

export const SAMPLE_QUESTIONS: Record<string, Question[]> = {
  "job-1": [
    {
      id: "q1-1",
      jobId: "job-1",
      question: "What hook is used for side effects in React?",
      options: ["useState", "useEffect", "useReducer", "useMemo"],
      correctAnswer: 1,
      timeLimit: 30,
    },
    {
      id: "q1-2",
      jobId: "job-1",
      question: "Which TypeScript utility type makes all properties optional?",
      options: ["Required", "Partial", "Pick", "Omit"],
      correctAnswer: 1,
      timeLimit: 25,
    },
    {
      id: "q1-3",
      jobId: "job-1",
      question:
        "What is the virtual DOM?",
      options: [
        "A direct copy of the browser DOM",
        "A lightweight JS representation of the real DOM",
        "A CSS rendering engine",
        "A server-side HTML parser",
      ],
      correctAnswer: 1,
      timeLimit: 30,
    },
    {
      id: "q1-4",
      jobId: "job-1",
      question: "Which CSS property creates a flex container?",
      options: [
        "display: block",
        "display: flex",
        "display: grid",
        "display: inline",
      ],
      correctAnswer: 1,
      timeLimit: 20,
    },
    {
      id: "q1-5",
      jobId: "job-1",
      question: "What does 'git rebase' do?",
      options: [
        "Merges two branches",
        "Reapplies commits on top of another base tip",
        "Deletes a branch",
        "Creates a new repository",
      ],
      correctAnswer: 1,
      timeLimit: 30,
    },
  ],
  "job-2": [
    {
      id: "q2-1",
      jobId: "job-2",
      question: "Which algorithm is commonly used for classification?",
      options: [
        "Linear Regression",
        "Random Forest",
        "K-Means Clustering",
        "PCA",
      ],
      correctAnswer: 1,
      timeLimit: 30,
    },
    {
      id: "q2-2",
      jobId: "job-2",
      question: "What does LSTM stand for?",
      options: [
        "Long Short-Term Memory",
        "Linear Sequential Training Model",
        "Least Squares Transformation Method",
        "Layered Semantic Text Mining",
      ],
      correctAnswer: 0,
      timeLimit: 25,
    },
    {
      id: "q2-3",
      jobId: "job-2",
      question: "Which library is used for data manipulation in Python?",
      options: ["NumPy", "Pandas", "Matplotlib", "Scikit-learn"],
      correctAnswer: 1,
      timeLimit: 20,
    },
    {
      id: "q2-4",
      jobId: "job-2",
      question: "What is overfitting?",
      options: [
        "Model performs well on both training and test data",
        "Model performs well on training data but poorly on test data",
        "Model performs poorly on all data",
        "Model has too few parameters",
      ],
      correctAnswer: 1,
      timeLimit: 30,
    },
  ],
  "job-3": [
    {
      id: "q3-1",
      jobId: "job-3",
      question: "What is the purpose of middleware in Express.js?",
      options: [
        "To serve static files",
        "To handle requests before they reach route handlers",
        "To compile TypeScript",
        "To manage database connections only",
      ],
      correctAnswer: 1,
      timeLimit: 30,
    },
    {
      id: "q3-2",
      jobId: "job-3",
      question: "Which HTTP method is used to update a resource?",
      options: ["GET", "POST", "PUT", "DELETE"],
      correctAnswer: 2,
      timeLimit: 20,
    },
    {
      id: "q3-3",
      jobId: "job-3",
      question: "What is Docker used for?",
      options: [
        "Version control",
        "Containerization of applications",
        "Database management",
        "Frontend rendering",
      ],
      correctAnswer: 1,
      timeLimit: 25,
    },
  ],
}
